# Generated by Django 4.1 on 2022-08-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_custom_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='application_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=20)),
                ('university_name', models.CharField(max_length=20)),
                ('program_name', models.CharField(max_length=20)),
                ('study_mode', models.CharField(max_length=20)),
                ('customer', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
