# Generated by Django 4.1 on 2022-09-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_application_model_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_model',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
